version: '3.3'


services:
  db:
    image: postgres:latest
    container_name: mango_db
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  web:
    build: ./
    container_name: mango_web
    restart: always
    command: sh -c 'python manage.py makemigrations && python manage.py migrate &&
      python manage.py collectstatic --no-input && gunicorn -b 0.0.0.0:8000 core.wsgi --reload'
    volumes:
      - '.:/mango_app'
      - './static:/mango_app/static'
      - './media:/mango_app/media'
    ports:
      - '8000:8000'
    depends_on:
      - db
  nginx:
    build: ./nginx
    container_name: mango_nginx
    restart: always
    volumes:
      - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
      - './media:/media'
      - './static:/static'
    depends_on:
      - web
    ports:
      - '80:80'
volumes:
  postgres_data:
    



