# Generated by Django 4.1.6 on 2023-02-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateField(auto_now_add=True, verbose_name="Дата регистрации"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateField(
                auto_now=True, default="2023-12-23", verbose_name="Последний логин"
            ),
            preserve_default=False,
        ),
    ]
