# Generated by Django 4.1.6 on 2023-02-21 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_user_email_alter_user_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="https://upload.wikimedia.org/wikipedia/commons/a/ac/Default_pfp.jpg",
                null=True,
                upload_to="",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg"]
                    )
                ],
                verbose_name="Фото профиля",
            ),
        ),
    ]
