# Generated by Django 4.1.6 on 2023-02-21 15:34

import api.users.utils
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="avatar",
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="users.basemodel",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        default="https://upload.wikimedia.org/wikipedia/commons/a/ac/Default_pfp.jpg",
                        null=True,
                        upload_to=api.users.utils.path_and_rename,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg"]
                            )
                        ],
                    ),
                ),
                ("profile_user_slug", models.SlugField(default="", unique=True)),
                (
                    "profile_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("users.basemodel",),
        ),
    ]
