# Generated by Django 4.1.6 on 2023-02-22 05:34

import api.users.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_basemodel_remove_user_avatar_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="https://upload.wikimedia.org/wikipedia/commons/a/ac/Default_pfp.jpg",
                null=True,
                upload_to=api.users.utils.path_and_rename,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(max_length=50, verbose_name="Прозвище"),
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
