# Generated by Django 4.1.6 on 2023-02-22 05:36

import api.users.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_avatar_alter_user_nickname_delete_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="https://upload.wikimedia.org/wikipedia/commons/a/ac/Default_pfp.jpg",
                null=True,
                upload_to=api.users.utils.path_and_rename,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "png", "img"]
                    )
                ],
            ),
        ),
    ]
